-- =====================================================
-- 에러 로깅 테이블 생성
-- 실행: Supabase SQL Editor에서 실행
-- =====================================================

-- 1. 에러 로그 테이블 생성
CREATE TABLE IF NOT EXISTS public.error_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT NOT NULL,
  stack TEXT,
  context JSONB,
  url TEXT,
  method VARCHAR(10),
  user_id UUID REFERENCES auth.users(id),
  severity VARCHAR(20) DEFAULT 'error', -- critical, error, warning, info
  resolved BOOLEAN DEFAULT FALSE,
  resolved_at TIMESTAMPTZ,
  resolved_by UUID REFERENCES auth.users(id),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 인덱스 추가 (조회 성능 최적화)
CREATE INDEX IF NOT EXISTS idx_error_logs_created_at ON error_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_error_logs_user_id ON error_logs(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_error_logs_severity ON error_logs(severity);
CREATE INDEX IF NOT EXISTS idx_error_logs_resolved ON error_logs(resolved);

-- 3. RLS 정책 설정
ALTER TABLE error_logs ENABLE ROW LEVEL SECURITY;

-- 정책: 관리자만 조회 가능
CREATE POLICY "Admin can view all errors"
  ON error_logs FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role IN ('master', 'admin')
    )
  );

-- 정책: 시스템(service role)은 삽입 가능
CREATE POLICY "System can insert errors"
  ON error_logs FOR INSERT
  TO service_role
  WITH CHECK (TRUE);

-- 정책: 관리자는 수정 가능 (해결 표시 등)
CREATE POLICY "Admin can update errors"
  ON error_logs FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role IN ('master', 'admin')
    )
  );

-- 4. 에러 요약 뷰 (선택사항)
CREATE OR REPLACE VIEW error_logs_summary AS
SELECT
  DATE_TRUNC('hour', created_at) as hour,
  severity,
  COUNT(*) as error_count,
  COUNT(DISTINCT user_id) as affected_users,
  COUNT(CASE WHEN resolved THEN 1 END) as resolved_count
FROM error_logs
WHERE created_at > NOW() - INTERVAL '7 days'
GROUP BY DATE_TRUNC('hour', created_at), severity
ORDER BY hour DESC, severity;

-- 5. 자동 정리 함수 (30일 이상 된 로그 삭제)
CREATE OR REPLACE FUNCTION cleanup_old_error_logs()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- 30일 이상 된 해결된 에러 로그 삭제
  DELETE FROM error_logs
  WHERE created_at < NOW() - INTERVAL '30 days'
  AND resolved = TRUE;

  -- 90일 이상 된 모든 에러 로그 삭제
  DELETE FROM error_logs
  WHERE created_at < NOW() - INTERVAL '90 days';
END;
$$;

-- 6. 크론 작업 설정 (pg_cron이 활성화된 경우)
-- 매일 새벽 3시에 정리 작업 실행
-- SELECT cron.schedule(
--   'cleanup-error-logs',
--   '0 3 * * *',
--   'SELECT cleanup_old_error_logs();'
-- );

-- 7. 권한 부여
GRANT SELECT ON error_logs_summary TO authenticated;

-- 8. 코멘트 추가
COMMENT ON TABLE error_logs IS '시스템 에러 로그 테이블';
COMMENT ON COLUMN error_logs.severity IS 'critical: 즉시 대응 필요, error: 일반 에러, warning: 경고, info: 정보';
COMMENT ON COLUMN error_logs.resolved IS '에러가 해결되었는지 여부';

-- =====================================================
-- 테스트 데이터 (선택사항)
-- =====================================================
-- INSERT INTO error_logs (message, severity, context)
-- VALUES
--   ('Test critical error', 'critical', '{"test": true}'::jsonb),
--   ('Test normal error', 'error', '{"test": true}'::jsonb),
--   ('Test warning', 'warning', '{"test": true}'::jsonb);