name: Database Backup

on:
  schedule:
    # 매일 새벽 2시 (KST 11시)
    - cron: '0 2 * * *'
  workflow_dispatch:  # 수동 실행 가능

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Validate secrets
      run: |
        if [ -z "${{ secrets.DB_HOST }}" ]; then
          echo "Error: DB_HOST secret is not set"
          exit 1
        fi
        if [ -z "${{ secrets.DB_PORT }}" ]; then
          echo "Error: DB_PORT secret is not set"
          exit 1
        fi
        if [ -z "${{ secrets.DB_USER }}" ]; then
          echo "Error: DB_USER secret is not set"
          exit 1
        fi
        if [ -z "${{ secrets.DB_PASSWORD }}" ]; then
          echo "Error: DB_PASSWORD secret is not set"
          exit 1
        fi
        if [ -z "${{ secrets.DB_NAME }}" ]; then
          echo "Error: DB_NAME secret is not set"
          exit 1
        fi
        echo "All required secrets are configured"

    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Test database connection
      env:
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        psql -h ${{ secrets.DB_HOST }} \
             -p ${{ secrets.DB_PORT }} \
             -U ${{ secrets.DB_USER }} \
             -d ${{ secrets.DB_NAME }} \
             -c "SELECT version();" || {
          echo "Error: Failed to connect to database"
          exit 1
        }
        echo "Database connection successful"

    - name: Create backup
      env:
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        DATE=$(date +%Y%m%d_%H%M%S)
        pg_dump \
          -h ${{ secrets.DB_HOST }} \
          -p ${{ secrets.DB_PORT }} \
          -U ${{ secrets.DB_USER }} \
          -d ${{ secrets.DB_NAME }} \
          -n aedpics \
          --no-owner \
          --no-acl \
          -f backup_${DATE}.sql

        if [ ! -f backup_${DATE}.sql ]; then
          echo "Error: Backup file was not created"
          exit 1
        fi

        BACKUP_SIZE=$(du -h backup_${DATE}.sql | cut -f1)
        echo "Backup file created: backup_${DATE}.sql (${BACKUP_SIZE})"

        gzip backup_${DATE}.sql
        echo "BACKUP_FILE=backup_${DATE}.sql.gz" >> $GITHUB_ENV

    - name: Upload backup to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: database-backup
        path: backup_*.sql.gz
        retention-days: 30

    - name: Notify backup success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            text: "Database backup completed",
            attachments: [{
              color: 'good',
              text: `Backup file: ${{ env.BACKUP_FILE }}`
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify backup failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            text: "Database backup failed",
            attachments: [{
              color: 'danger',
              text: "Failed to create database backup"
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
